---
abstract: 'Gather files and their metadata together in one place'
author:
  - 'Paul Hoffman <paul@flo.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Kit
requires:
  File::Copy: 0
  File::Kvpar: 0
  Getopt::Long: 0
  constant: 0
  strict: 0
  vars: 0
  warnings: 0
version: 0.03
